In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [ ]:
df=pd.read_csv('/content/1ToyotaCorolla.csv')

In [ ]:
df.head

<bound method NDFrame.head of                                                   model  price  age_08_04  \
0         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500         23   
1         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750         23   
2         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950         24   
3         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950         26   
4           TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750         30   
...                                                 ...    ...        ...   
1431         TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors   7500         69   
1432  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...  10845         72   
1433  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   8500         71   
1434  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   7250         70   
1435        TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors   6950         76   

      mfg_month  mfg_year     km fuel_type   

In [ ]:
df.info

<bound method DataFrame.info of                                                   model  price  age_08_04  \
0         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500         23   
1         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750         23   
2         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950         24   
3         TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950         26   
4           TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750         30   
...                                                 ...    ...        ...   
1431         TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors   7500         69   
1432  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...  10845         72   
1433  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   8500         71   
1434  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   7250         70   
1435        TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors   6950         76   

      mfg_month  mfg_year     km fuel_type 

We'llConsider only the below columns and prepare a prediction model for predicting Price.

("Price","Age_08_04","KM","HP","cc","Doors","Gears","Quarterly_Tax","Weight")



In [ ]:
df.columns

Index(['model', 'price', 'age_08_04', 'mfg_month', 'mfg_year', 'km',
       'fuel_type', 'hp', 'met_color', 'color', 'automatic', 'cc', 'doors',
       'cylinders', 'gears', 'quarterly_tax', 'weight', 'mfr_guarantee',
       'bovag_guarantee', 'guarantee_period', 'abs', 'airbag_1', 'airbag_2',
       'airco', 'automatic_airco', 'boardcomputer', 'cd_player',
       'central_lock', 'powered_windows', 'power_steering', 'radio',
       'mistlamps', 'sport_model', 'backseat_divider', 'metallic_rim',
       'radio_cassette', 'parking_assistant', 'tow_bar'],
      dtype='object')

In [ ]:
df=df.iloc[:,[1,2,5,7,11,12,14,15,16]]

In [ ]:
df

price  age_08_04     km   hp    cc  doors  gears  quarterly_tax  weight
0     13500         23  46986   90  2000      3      5            210    1165
1     13750         23  72937   90  2000      3      5            210    1165
2     13950         24  41711   90  2000      3      5            210    1165
3     14950         26  48000   90  2000      3      5            210    1165
4     13750         30  38500   90  2000      3      5            210    1170
...     ...        ...    ...  ...   ...    ...    ...            ...     ...
1431   7500         69  20544   86  1300      3      5             69    1025
1432  10845         72  19000   86  1300      3      5             69    1015
1433   8500         71  17016   86  1300      3      5             69    1015
1434   7250         70  16916   86  1300      3      5             69    1015
1435   6950         76      1  110  1600      5      5             19    1114

[1436 rows x 9 columns]

Split Data into IV or DV

In [ ]:
x=df.iloc[:,[1,2,3,4,5,6,7,8]].values

In [ ]:
x

array([[   23, 46986,    90, ...,     5,   210,  1165],
       [   23, 72937,    90, ...,     5,   210,  1165],
       [   24, 41711,    90, ...,     5,   210,  1165],
       ...,
       [   71, 17016,    86, ...,     5,    69,  1015],
       [   70, 16916,    86, ...,     5,    69,  1015],
       [   76,     1,   110, ...,     5,    19,  1114]])

In [ ]:
y=df.iloc[:,[0]].values

In [ ]:
y

array([[13500],
       [13750],
       [13950],
       ...,
       [ 8500],
       [ 7250],
       [ 6950]])

In [ ]:
x.shape

(1436, 8)

In [ ]:
x.ndim

2

In [ ]:
y.shape

(1436, 1)

In [ ]:
y.ndim

2

**Split data into training & testing dataset**

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=1200)

In [ ]:
x_train.shape

(1148, 8)

In [ ]:
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(288, 8)
(1148, 1)
(288, 1)


**Fitting Multiple linear regression to training dataset**

In [ ]:
regg=LinearRegression()

In [ ]:
regg.fit(x_train,y_train)

LinearRegression()

In [ ]:
regg.intercept_

array([-5439.99003263])

In [ ]:
regg.score(x_test,y_test)

0.8723630328786833

In [ ]:
regg.score(x_train,y_train)

0.8611080182384747

In [ ]:
y_pred=regg.predict(x_test)

In [ ]:
print(r2_score(y_test, y_pred))

0.8723630328786833


Predicting on test dataset

In [ ]:
y_predict=regg.predict(x_test)
print(y_predict)

[[ 9670.75516351]
 [16663.88533233]
 [ 9952.42514308]
 [ 8261.87393766]
 [ 9654.41486267]
 [17164.78060641]
 [ 8335.99184461]
 [12643.07416017]
 [ 9583.76223717]
 [11275.19302172]
 [ 7200.73508454]
 [ 7858.48081642]
 [11877.69295548]
 [ 8610.42538723]
 [ 9458.88547039]
 [ 7649.60963839]
 [10971.94435062]
 [ 9793.02614223]
 [15823.26241573]
 [10942.37007908]
 [18801.71546359]
 [ 8709.0531973 ]
 [ 9441.91876847]
 [17865.21989979]
 [11519.43374778]
 [10254.71980546]
 [ 6267.16303704]
 [ 9771.82615458]
 [16295.62503712]
 [ 4542.2949003 ]
 [14856.51537914]
 [18962.25779199]
 [16273.65865519]
 [10054.19854404]
 [17331.38725364]
 [19272.70222841]
 [10889.60406999]
 [16631.23954163]
 [12937.86214194]
 [ 8213.8751966 ]
 [22268.18852957]
 [ 9500.98056906]
 [ 8155.27614923]
 [11417.37840389]
 [ 5513.22131033]
 [ 6619.80534756]
 [ 8830.11839419]
 [10524.19618173]
 [ 8754.08161592]
 [ 7952.97341669]
 [ 7945.53251675]
 [ 9701.70782731]
 [ 7905.94181263]
 [16655.89235577]
 [12219.5875324 ]
 [21331.00